name       : syncplay
version    : 1.5.2
release    : 3
source     :
    - https://github.com/Syncplay/syncplay/archive/v1.5.2.tar.gz : 8a6a6e73b28e842230b4deef3b031f8ebeea5e30ffca393f2c4f8de207c6f428
license    : Apache-2.0
component  : multimedia.video
summary    : Synchronises media players so that distant friends can watch videos together
description: |
    Syncplay keeps your media players in sync so that one may watch videos with friends.
rundeps    :
    - python-pyside
    - python-twisted
    - python-zope.interface
setup      : |
    sed -i '45s/$/hicolor\//' GNUmakefile && mkdir -p $installdir/usr/share/icons
install    : |
    %make_install LIB_PATH=$installdir/%libdir% \
                  VLC_LIB_PATH=$installdir/%libdir%
    rm -rf $installdir/usr/share/{app-install,pixmaps}